---

- name: Baseline import os-specific tasks
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"

- name: Baseline | install .vimrc
  ansible.builtin.copy:
    src: .vimrc
    dest: /home/jopitz/.vimrc
    owner: jopitz
    group: jopitz
    mode: 0644

- name: Baseline | import ssh configuration
  ansible.builtin.include_tasks: ssh.yaml
